parameters:
    connection: live #sandbox or live type of connection
    show_errors: true
    report_assets: assets
    storage_path: storage
    proxy_path: proxy

sensio_buzz:
    client_timeout: 180